root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = []
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  log = "build-errors.log"

[log]
  main_only = false
  time = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true